#!/usr/bin/env python3
"""Audit source/render/output alignment for TES public documentation surfaces."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
STRUCTURE = Path("docs/i18n/tes-public.structure.yml")
CONTENT = Path("docs/i18n/tes-public.content.json")
MINI_PROMPT = Path("docs/install/MINI-PROMPT.md")
DOCS_INDEX = Path("docs/INDEX.md")
TDS_SPEC = Path("docs/tds/TDS-SPEC.md")
TDS_INDEX = Path("docs/tds/DOCS-INDEX.yml")
RENDERER = Path("scripts/build_public_docs.py")
GENERATED_MARKER = (
    "<!-- Generated by scripts/build_public_docs.py from "
    "docs/i18n/tes-public.structure.yml and docs/i18n/tes-public.content.json. -->"
)
PRINCIPLE_LINES = (
    "The source is the contract.",
    "The rendered document is evidence.",
    "The module graph is the memory.",
    "The generated surface must never become the hidden source.",
)
PUBLIC_INSTALLER_INTERNAL_SNIPPETS = (
    "npm account",
    "conta npm",
    "cuenta npm",
    "npm registry",
    "npm dist-tag",
    "private:true",
    "thin wrapper",
    "wrapper fino",
    "wrapper node",
    "node cli",
    "python installer",
    "instalador python",
    "motor python",
    "certified python",
    "python certificado",
    "direct python form",
    "thin node",
    "tes_install.py install",
)


@dataclass
class Finding:
    severity: str
    code: str
    message: str
    path: str | None = None

    def as_dict(self) -> dict[str, str]:
        data = {"severity": self.severity, "code": self.code, "message": self.message}
        if self.path:
            data["path"] = self.path
        return data


def rel(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def load_jsonish(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        try:
            import yaml  # type: ignore
        except ModuleNotFoundError as exc:
            raise ValueError(f"{path} is not JSON and PyYAML is unavailable") from exc
        data = yaml.safe_load(text)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must load as an object")
    return data


def fenced_block(markdown: str, fence: str) -> str | None:
    match = re.search(rf"```{re.escape(fence)}\n(.*?)\n```", markdown, re.S)
    return match.group(1) if match else None


def hard_wrap_suspects(payload: str) -> list[str]:
    suspects: list[str] = []
    for paragraph in re.split(r"\n\s*\n", payload.strip()):
        lines = paragraph.splitlines()
        if len(lines) < 2:
            continue
        for index, line in enumerate(lines[:-1]):
            current = line.rstrip()
            nxt = lines[index + 1].lstrip()
            if not nxt:
                continue
            if len(current) < 64 or len(current) > 104:
                continue
            if current.endswith((".", ":", ";", "!", "?", "`", ")", "]")):
                continue
            if re.match(r"^[a-z0-9`]", nxt):
                suspects.append(current)
    return suspects


def render_check(root: Path) -> Finding:
    result = subprocess.run(
        [sys.executable, str(root / RENDERER), "--check"],
        cwd=root,
        text=True,
        capture_output=True,
        timeout=120,
        check=False,
    )
    if result.returncode == 0:
        return Finding("PASS", "renderer_check_passed", "Public docs renderer check passed.", RENDERER.as_posix())
    tail = "\n".join((result.stdout + "\n" + result.stderr).strip().splitlines()[-8:])
    return Finding("BLOCKER", "renderer_check_failed", f"Public docs renderer check failed: {tail}", RENDERER.as_posix())


def collect_prompt_sources(content: dict[str, Any]) -> list[tuple[str, str]]:
    sources: list[tuple[str, str]] = []

    def walk(value: Any) -> None:
        if isinstance(value, dict):
            if value.get("type") == "prompt_copy" and value.get("source"):
                sources.append((str(value["source"]), str(value.get("fence", "text"))))
            for item in value.values():
                walk(item)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    walk(content)
    deduped: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for source in sources:
        if source not in seen:
            seen.add(source)
            deduped.append(source)
    return deduped


def collect_prompt_source_instances(content: dict[str, Any]) -> list[tuple[str, str]]:
    sources: list[tuple[str, str]] = []

    def walk(value: Any) -> None:
        if isinstance(value, dict):
            if value.get("type") == "prompt_copy" and value.get("source"):
                sources.append((str(value["source"]), str(value.get("fence", "text"))))
            for item in value.values():
                walk(item)
        elif isinstance(value, list):
            for item in value:
                walk(item)

    walk(content)
    return sources


def indexed_markdown_paths(root: Path) -> set[str]:
    text = (root / TDS_INDEX).read_text(encoding="utf-8")
    return set(re.findall(r"^\s*-\s+path:\s+(docs/[^\n]+\.md)\s*$", text, re.M))


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def forbidden_public_installer_terms(text: str) -> list[str]:
    lowered = text.casefold()
    return [
        snippet
        for snippet in PUBLIC_INSTALLER_INTERNAL_SNIPPETS
        if snippet.casefold() in lowered
    ]


def code_copy_button_failures(text: str) -> list[str]:
    failures: list[str] = []
    for index, match in enumerate(
        re.finditer(r'<div class="pre-wrap"(?P<attrs>[^>]*)>(?P<body>.*?)</div>', text, re.S),
        start=1,
    ):
        attrs = match.group("attrs")
        body = match.group("body")
        label_match = re.search(r'data-label="([^"]+)"', attrs)
        label = html.unescape(label_match.group(1)) if label_match else f"code card {index}"
        if "data-copy-block" not in attrs:
            failures.append(f"{label}: missing data-copy-block")
            continue
        if "data-copy-button" not in body:
            failures.append(f"{label}: missing copy button")
            continue
        if 'data-copy-icon="true"' not in body or "<svg" not in body:
            failures.append(f"{label}: missing SVG copy button")
    return failures


def same_page_anchor_failures(text: str) -> list[str]:
    static_text = re.sub(r"<script\b[^>]*>.*?</script>", "", text, flags=re.S | re.I)
    ids = {html.unescape(match.group(1)) for match in re.finditer(r'\bid="([^"]+)"', static_text)}
    failures: list[str] = []
    for match in re.finditer(r'<a\b[^>]*\bhref="(#[^"]*)"', static_text):
        href = html.unescape(match.group(1)).split("?", 1)[0]
        if not href or href == "#" or href.startswith("#/"):
            continue
        anchor = href[1:]
        if anchor and anchor not in ids and href not in failures:
            failures.append(href)
    return failures


def textareas_for_prompt(output_text: str) -> list[str]:
    return [
        html.unescape(match.group(1))
        for match in re.finditer(
            r'<textarea class="copy-source" data-copy-source readonly aria-hidden="true" tabindex="-1">(.*?)</textarea>',
            output_text,
            re.S,
        )
    ]


def manifest(root: Path) -> dict[str, Any]:
    structure = load_jsonish(root / STRUCTURE)
    content_path = Path(structure.get("sources", {}).get("content", CONTENT.as_posix()))
    structure_path = Path(structure.get("sources", {}).get("structure", STRUCTURE.as_posix()))
    outputs: list[str] = [str(item) for item in structure.get("generated_outputs", [])]
    for page in structure.get("pages", {}).values():
        if isinstance(page, dict) and page.get("output"):
            outputs.append(str(page["output"]))
    seen: set[str] = set()
    outputs = [item for item in outputs if not (item in seen or seen.add(item))]
    return {
        "root": root.as_posix(),
        "source": {
            "content": content_path.as_posix(),
            "canonical_payload": MINI_PROMPT.as_posix(),
            "tds_spec": TDS_SPEC.as_posix(),
            "tds_index": TDS_INDEX.as_posix(),
        },
        "module_graph": structure_path.as_posix(),
        "renderer": RENDERER.as_posix(),
        "generated_outputs": outputs,
        "runtime_routes": {
            "landing": "/tilly-engineer-skills/",
            "manual": "/tilly-engineer-skills/install/USER-MANUAL.html",
            "health": "/_tds/health",
            "manifest": "/_tds/manifest",
            "check": "/_tds/check",
            "legacy_health": "/__tds__/health",
        },
    }


def audit(root: Path, run_render_check: bool = True) -> tuple[str, dict[str, Any], list[Finding]]:
    root = root.resolve()
    findings: list[Finding] = []

    required = (STRUCTURE, CONTENT, MINI_PROMPT, DOCS_INDEX, TDS_SPEC, TDS_INDEX, RENDERER)
    for path in required:
        if (root / path).exists():
            findings.append(Finding("PASS", "required_surface_file_found", "Required source/render file exists.", path.as_posix()))
        else:
            findings.append(Finding("BLOCKER", "required_surface_file_missing", "Required source/render file is missing.", path.as_posix()))

    if any(item.severity == "BLOCKER" for item in findings):
        return "FAIL", {"root": root.as_posix()}, findings

    structure = load_jsonish(root / STRUCTURE)
    content = load_jsonish(root / CONTENT)
    current_manifest = manifest(root)

    content_text = (root / CONTENT).read_text(encoding="utf-8", errors="replace")
    content_offenders = forbidden_public_installer_terms(content_text)
    if content_offenders:
        findings.append(
            Finding(
                "BLOCKER",
                "public_installer_internal_detail",
                f"Public installer copy exposes maintainer/distribution detail: {', '.join(content_offenders)}.",
                CONTENT.as_posix(),
            )
        )
    else:
        findings.append(
            Finding(
                "PASS",
                "public_installer_contract_sanitized",
                "Public installer copy states user-visible contract instead of maintainer internals.",
                CONTENT.as_posix(),
            )
        )

    declared_structure = structure.get("sources", {}).get("structure")
    declared_content = structure.get("sources", {}).get("content")
    if declared_structure == STRUCTURE.as_posix() and declared_content == CONTENT.as_posix():
        findings.append(Finding("PASS", "module_graph_declares_sources", "Module graph declares its structure and content sources.", STRUCTURE.as_posix()))
    else:
        findings.append(Finding("BLOCKER", "module_graph_source_mismatch", "Module graph does not declare the canonical structure/content sources.", STRUCTURE.as_posix()))

    output_paths = [Path(item) for item in current_manifest["generated_outputs"]]
    if output_paths:
        findings.append(Finding("PASS", "generated_outputs_declared", "Module graph declares generated outputs.", STRUCTURE.as_posix()))
    else:
        findings.append(Finding("BLOCKER", "generated_outputs_missing", "Module graph declares no generated outputs.", STRUCTURE.as_posix()))

    for output in output_paths:
        path = root / output
        if not path.exists():
            findings.append(Finding("BLOCKER", "generated_output_missing", "Generated output is missing.", output.as_posix()))
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        output_offenders = forbidden_public_installer_terms(html.unescape(text))
        if output_offenders:
            findings.append(
                Finding(
                    "BLOCKER",
                    "public_installer_internal_detail",
                    f"Generated public surface exposes maintainer/distribution detail: {', '.join(output_offenders)}.",
                    output.as_posix(),
                )
            )
        else:
            findings.append(
                Finding(
                    "PASS",
                    "public_installer_contract_rendered",
                    "Generated public surface keeps installer copy at the user-visible contract layer.",
                    output.as_posix(),
                )
            )
        copy_failures = code_copy_button_failures(text)
        if copy_failures:
            findings.append(
                Finding(
                    "BLOCKER",
                    "public_code_copy_button_missing",
                    f"Generated code cards need SVG copy buttons: {copy_failures[0]}.",
                    output.as_posix(),
                )
            )
        else:
            code_cards = len(re.findall(r'<div class="pre-wrap"', text))
            findings.append(
                Finding(
                    "PASS",
                    "public_code_copy_buttons_present",
                    f"Generated code cards carry SVG copy buttons ({code_cards} found).",
                    output.as_posix(),
                )
            )
        anchor_failures = same_page_anchor_failures(text)
        if anchor_failures:
            findings.append(
                Finding(
                    "BLOCKER",
                    "same_page_anchor_missing",
                    f"Generated same-page links point to missing anchors: {', '.join(anchor_failures[:5])}.",
                    output.as_posix(),
                )
            )
        else:
            findings.append(
                Finding(
                    "PASS",
                    "same_page_anchors_resolve",
                    "Generated same-page links resolve to existing anchors.",
                    output.as_posix(),
                )
            )
        if GENERATED_MARKER not in text[:512]:
            findings.append(Finding("BLOCKER", "generated_marker_missing", "Generated output lacks the canonical source marker.", output.as_posix()))
        else:
            findings.append(Finding("PASS", "generated_marker_matches", "Generated output names renderer and source graph.", output.as_posix()))
        if "Generated from JSON + YAML" in text:
            findings.append(Finding("BLOCKER", "implementation_detail_as_authority", "Generated output exposes implementation detail as authority.", output.as_posix()))
        if "Generated from TDS" in text or "Gerado a partir do TDS" in text or "Generado desde TDS" in text:
            findings.append(Finding("PASS", "tds_public_label_present", "Generated output carries a TDS public source label.", output.as_posix()))
        else:
            findings.append(Finding("WARN", "tds_public_label_missing", "Generated output has no visible TDS source label.", output.as_posix()))

    package_path = root / "package.json"
    if package_path.exists():
        package = json.loads(package_path.read_text(encoding="utf-8"))
        if package.get("version") == structure.get("version"):
            findings.append(Finding("PASS", "version_matches_structure", "Package version matches public docs structure version.", "package.json"))
        else:
            findings.append(Finding("BLOCKER", "version_structure_mismatch", "Package version differs from public docs structure version.", "package.json"))

    bundle_sha = str(structure.get("evidence", {}).get("bundle_sha256", ""))
    version = str(structure.get("version", ""))
    if bundle_sha and version:
        zip_path = root / f"docs/dist/{version}/tilly-engineer-skills-{version}.zip"
        sidecar_path = root / f"docs/dist/{version}/tilly-engineer-skills-{version}.zip.sha256"
        if zip_path.exists() and sidecar_path.exists():
            actual = sha256(zip_path)
            sidecar = sidecar_path.read_text(encoding="utf-8").split()[0]
            if bundle_sha == sidecar == actual:
                findings.append(Finding("PASS", "bundle_sha_matches", "Public docs bundle SHA matches structure, sidecar, and ZIP.", sidecar_path.relative_to(root).as_posix()))
            else:
                findings.append(Finding("BLOCKER", "bundle_sha_mismatch", "Public docs bundle SHA differs from structure, sidecar, or ZIP.", sidecar_path.relative_to(root).as_posix()))
        else:
            findings.append(Finding("WARN", "bundle_artifact_missing", "Declared public bundle artifact or SHA sidecar is missing.", f"docs/dist/{version}"))

    languages = [str(item.get("code")) for item in structure.get("languages", []) if isinstance(item, dict) and item.get("code")]
    sections = content.get("sections", {})
    if isinstance(sections, dict) and languages:
        for section_key, localized in sections.items():
            if not isinstance(localized, dict):
                continue
            missing_langs = [lang for lang in languages if lang not in localized]
            if missing_langs:
                findings.append(Finding("BLOCKER", "i18n_section_missing_language", f"Section {section_key} is missing languages: {', '.join(missing_langs)}.", CONTENT.as_posix()))
                continue
            shapes: dict[str, list[str]] = {}
            for lang in languages:
                blocks = localized.get(lang, {}).get("blocks", [])
                if isinstance(blocks, list):
                    shapes[lang] = [str(block.get("type", "?")) for block in blocks if isinstance(block, dict)]
            if len({tuple(shape) for shape in shapes.values()}) > 1:
                findings.append(Finding("WARN", "i18n_block_shape_differs", f"Section {section_key} has different block type sequences across languages.", CONTENT.as_posix()))
        findings.append(Finding("PASS", "i18n_sections_have_languages", "Public docs sections expose all configured languages.", CONTENT.as_posix()))

    indexed_paths = indexed_markdown_paths(root)
    for output in output_paths:
        output_path = root / output
        if not output_path.exists():
            continue
        html_text = output_path.read_text(encoding="utf-8", errors="replace")
        doc_links = sorted(set(re.findall(r'data-doc-link="([^"]+)"', html_text)))
        if not doc_links:
            continue
        missing_docs: list[str] = []
        missing_index: list[str] = []
        for slug in doc_links:
            markdown_path = f"docs/{slug}.md"
            if not (root / markdown_path).exists():
                missing_docs.append(markdown_path)
            if markdown_path not in indexed_paths:
                missing_index.append(markdown_path)
        if missing_docs:
            findings.append(Finding("BLOCKER", "runtime_doc_route_missing_file", f"Runtime doc links point to missing files: {', '.join(missing_docs[:5])}.", output.as_posix()))
        if missing_index:
            findings.append(Finding("BLOCKER", "runtime_doc_route_not_indexed", f"Runtime doc links are not TDS-indexed: {', '.join(missing_index[:5])}.", output.as_posix()))
        if not missing_docs and not missing_index:
            findings.append(Finding("PASS", "runtime_doc_routes_indexed", f"Runtime doc links exist and are TDS-indexed ({len(doc_links)} links).", output.as_posix()))

    prompt_instances = collect_prompt_source_instances(content)
    if not prompt_instances:
        findings.append(Finding("PASS", "copy_payload_not_public", "Public surface does not expose an installation prompt copy payload.", CONTENT.as_posix()))
    elif len(prompt_instances) == len(languages) and all(source == MINI_PROMPT.as_posix() for source, _ in prompt_instances):
        findings.append(Finding("PASS", "copy_payload_declared_per_language", "Each configured language declares the canonical mini prompt source.", CONTENT.as_posix()))
    else:
        findings.append(Finding("WARN", "copy_payload_language_shape_unexpected", "Prompt-copy declarations do not match configured language count.", CONTENT.as_posix()))

    prompt_sources = collect_prompt_sources(content)
    if prompt_sources:
        findings.append(Finding("PASS", "copy_payload_source_declared", "Content source declares copy-ready payload source.", CONTENT.as_posix()))
    else:
        findings.append(Finding("PASS", "copy_payload_source_not_required", "No public copy-ready prompt payload is declared.", CONTENT.as_posix()))

    for source, fence in prompt_sources:
        source_path = root / source
        if not source_path.exists():
            findings.append(Finding("BLOCKER", "copy_payload_missing", "Declared copy-ready payload is missing.", source))
            continue
        payload = fenced_block(source_path.read_text(encoding="utf-8"), fence)
        if payload is None:
            findings.append(Finding("BLOCKER", "copy_payload_fence_missing", "Declared copy-ready payload lacks the expected fence.", source))
            continue
        suspects = hard_wrap_suspects(payload)
        if suspects:
            findings.append(Finding("BLOCKER", "copy_payload_hard_wrapped", f"Copy-ready payload appears hard-wrapped near: {suspects[0]}", source))
        else:
            findings.append(Finding("PASS", "copy_payload_not_hard_wrapped", "Copy-ready payload is fenced without forced prose wrapping.", source))
        for output in output_paths:
            output_text = (root / output).read_text(encoding="utf-8", errors="replace") if (root / output).exists() else ""
            rendered_payloads = textareas_for_prompt(output_text)
            if rendered_payloads and all(item == payload for item in rendered_payloads):
                findings.append(Finding("PASS", "copy_payload_rendered_exactly", f"Generated output preserves exact copy payload in all hidden copy sources ({len(rendered_payloads)}).", output.as_posix()))
            elif rendered_payloads:
                findings.append(Finding("BLOCKER", "copy_payload_drift", "Generated output copy source differs from canonical payload.", output.as_posix()))

    docs_index = (root / DOCS_INDEX).read_text(encoding="utf-8")
    for needle in (STRUCTURE.as_posix(), CONTENT.as_posix(), RENDERER.as_posix(), "source/render/output"):
        if needle in docs_index:
            findings.append(Finding("PASS", "docs_index_maps_public_surface", f"Docs index maps {needle}.", DOCS_INDEX.as_posix()))
        else:
            findings.append(Finding("WARN", "docs_index_surface_map_incomplete", f"Docs index does not mention {needle}.", DOCS_INDEX.as_posix()))

    tds_spec = (root / TDS_SPEC).read_text(encoding="utf-8")
    for line in PRINCIPLE_LINES:
        if line in tds_spec:
            findings.append(Finding("PASS", "tds_principle_present", f"TDS spec states: {line}", TDS_SPEC.as_posix()))
        else:
            findings.append(Finding("WARN", "tds_principle_missing", f"TDS spec does not state: {line}", TDS_SPEC.as_posix()))

    if run_render_check:
        findings.append(render_check(root))

    blockers = [item for item in findings if item.severity == "BLOCKER"]
    return ("FAIL" if blockers else "PASS"), current_manifest, findings


def render_text(status: str, current_manifest: dict[str, Any], findings: list[Finding]) -> str:
    lines = [
        f"[tds-surface] {status}",
        f"root={current_manifest.get('root', ROOT.as_posix())}",
        f"module_graph={current_manifest.get('module_graph', STRUCTURE.as_posix())}",
        f"renderer={current_manifest.get('renderer', RENDERER.as_posix())}",
        "generated_outputs:",
    ]
    for output in current_manifest.get("generated_outputs", []):
        lines.append(f"- {output}")
    lines.append("findings:")
    for finding in findings:
        suffix = f" ({finding.path})" if finding.path else ""
        lines.append(f"- [{finding.severity}] {finding.code}: {finding.message}{suffix}")
    return "\n".join(lines)


def self_test() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for path in ("docs/i18n", "docs/install", "docs/tds", "scripts"):
            (root / path).mkdir(parents=True, exist_ok=True)
        (root / STRUCTURE).write_text(
            json.dumps(
                {
                    "sources": {"content": CONTENT.as_posix(), "structure": STRUCTURE.as_posix()},
                    "generated_outputs": ["docs/index.html", "docs/install/USER-MANUAL.html"],
                    "pages": {},
                }
            ),
            encoding="utf-8",
        )
        (root / CONTENT).write_text(
            json.dumps({"blocks": [{"type": "prompt_copy", "source": MINI_PROMPT.as_posix(), "fence": "text"}]}),
            encoding="utf-8",
        )
        payload = "Install safely from the canonical prompt source."
        (root / MINI_PROMPT).write_text(f"---\nsource_of_truth: true\n---\n\n```text\n{payload}\n```\n", encoding="utf-8")
        for doc in (DOCS_INDEX, TDS_INDEX):
            (root / doc).write_text(
                "source/render/output\n"
                f"{STRUCTURE.as_posix()}\n{CONTENT.as_posix()}\n{RENDERER.as_posix()}\n",
                encoding="utf-8",
            )
        (root / TDS_SPEC).write_text("\n".join(PRINCIPLE_LINES), encoding="utf-8")
        marker = GENERATED_MARKER + "\n"
        textarea = f'<textarea class="copy-source" data-copy-source readonly aria-hidden="true" tabindex="-1">{html.escape(payload)}</textarea>'
        code_card = (
            '<div class="pre-wrap" data-label="fixed" data-copy-block>'
            '<button data-copy-button data-copy-icon="true"><svg></svg></button>'
            "<pre><code>tes command</code></pre></div>"
        )
        for output in ("docs/index.html", "docs/install/USER-MANUAL.html"):
            (root / output).parent.mkdir(parents=True, exist_ok=True)
            (root / output).write_text(marker + "Generated from TDS." + textarea + code_card, encoding="utf-8")
        (root / RENDERER).write_text("#!/usr/bin/env python3\nimport sys\nsys.exit(0)\n", encoding="utf-8")
        status, current_manifest, findings = audit(root)
        if status != "PASS":
            raise AssertionError(render_text(status, current_manifest, findings))

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for path in ("docs/i18n", "docs/install", "docs/tds", "scripts"):
            (root / path).mkdir(parents=True, exist_ok=True)
        (root / STRUCTURE).write_text(
            json.dumps({"sources": {"content": CONTENT.as_posix(), "structure": STRUCTURE.as_posix()}, "generated_outputs": ["docs/index.html"]}),
            encoding="utf-8",
        )
        (root / CONTENT).write_text(json.dumps({"type": "prompt_copy", "source": MINI_PROMPT.as_posix(), "fence": "text"}), encoding="utf-8")
        hard = "This payload line is deliberately wrapped before it reaches any semantic boundary\nand should fail the oracle."
        (root / MINI_PROMPT).write_text(f"```text\n{hard}\n```\n", encoding="utf-8")
        (root / DOCS_INDEX).write_text("", encoding="utf-8")
        (root / TDS_INDEX).write_text("", encoding="utf-8")
        (root / TDS_SPEC).write_text("", encoding="utf-8")
        (root / "docs/index.html").write_text("<!-- generated elsewhere -->\n", encoding="utf-8")
        (root / RENDERER).write_text("#!/usr/bin/env python3\nimport sys\nsys.exit(0)\n", encoding="utf-8")
        status, _, findings = audit(root, run_render_check=False)
        codes = {finding.code for finding in findings}
        if status != "FAIL" or "generated_marker_missing" not in codes or "copy_payload_hard_wrapped" not in codes:
            raise AssertionError(render_text(status, manifest(root), findings))

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for path in ("docs/i18n", "docs/install", "docs/tds", "scripts"):
            (root / path).mkdir(parents=True, exist_ok=True)
        (root / STRUCTURE).write_text(
            json.dumps(
                {
                    "sources": {"content": CONTENT.as_posix(), "structure": STRUCTURE.as_posix()},
                    "generated_outputs": ["docs/index.html"],
                    "pages": {},
                }
            ),
            encoding="utf-8",
        )
        (root / CONTENT).write_text(
            json.dumps({"copy": "No npm account is required because the Node CLI is a thin wrapper."}),
            encoding="utf-8",
        )
        (root / MINI_PROMPT).write_text("```text\nInstall safely.\n```\n", encoding="utf-8")
        for doc in (DOCS_INDEX, TDS_INDEX):
            (root / doc).write_text("", encoding="utf-8")
        (root / TDS_SPEC).write_text("", encoding="utf-8")
        (root / "docs/index.html").write_text(GENERATED_MARKER + "\nGenerated from TDS.", encoding="utf-8")
        (root / RENDERER).write_text("#!/usr/bin/env python3\nimport sys\nsys.exit(0)\n", encoding="utf-8")
        status, _, findings = audit(root, run_render_check=False)
        codes = {finding.code for finding in findings}
        if status != "FAIL" or "public_installer_internal_detail" not in codes:
            raise AssertionError(render_text(status, manifest(root), findings))

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for path in ("docs/i18n", "docs/install", "docs/tds", "scripts"):
            (root / path).mkdir(parents=True, exist_ok=True)
        (root / STRUCTURE).write_text(
            json.dumps(
                {
                    "sources": {"content": CONTENT.as_posix(), "structure": STRUCTURE.as_posix()},
                    "generated_outputs": ["docs/index.html"],
                    "pages": {},
                }
            ),
            encoding="utf-8",
        )
        (root / CONTENT).write_text(json.dumps({"copy": "Run the installer."}), encoding="utf-8")
        (root / MINI_PROMPT).write_text("```text\nInstall safely.\n```\n", encoding="utf-8")
        for doc in (DOCS_INDEX, TDS_INDEX):
            (root / doc).write_text("", encoding="utf-8")
        (root / TDS_SPEC).write_text("", encoding="utf-8")
        (root / "docs/index.html").write_text(
            GENERATED_MARKER
            + '\nGenerated from TDS.<div class="pre-wrap" data-label="fixed"><pre><code>tes command</code></pre></div>',
            encoding="utf-8",
        )
        (root / RENDERER).write_text("#!/usr/bin/env python3\nimport sys\nsys.exit(0)\n", encoding="utf-8")
        status, _, findings = audit(root, run_render_check=False)
        codes = {finding.code for finding in findings}
        if status != "FAIL" or "public_code_copy_button_missing" not in codes:
            raise AssertionError(render_text(status, manifest(root), findings))

    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp)
        for path in ("docs/i18n", "docs/install", "docs/tds", "scripts"):
            (root / path).mkdir(parents=True, exist_ok=True)
        (root / STRUCTURE).write_text(
            json.dumps(
                {
                    "sources": {"content": CONTENT.as_posix(), "structure": STRUCTURE.as_posix()},
                    "generated_outputs": ["docs/index.html"],
                    "pages": {},
                }
            ),
            encoding="utf-8",
        )
        (root / CONTENT).write_text(json.dumps({"copy": "Run the installer."}), encoding="utf-8")
        (root / MINI_PROMPT).write_text("```text\nInstall safely.\n```\n", encoding="utf-8")
        for doc in (DOCS_INDEX, TDS_INDEX):
            (root / doc).write_text("", encoding="utf-8")
        (root / TDS_SPEC).write_text("", encoding="utf-8")
        (root / "docs/index.html").write_text(
            GENERATED_MARKER
            + '\nGenerated from TDS.<main id="content"><a class="btn btn-primary" href="#start">Install</a></main>',
            encoding="utf-8",
        )
        (root / RENDERER).write_text("#!/usr/bin/env python3\nimport sys\nsys.exit(0)\n", encoding="utf-8")
        status, _, findings = audit(root, run_render_check=False)
        codes = {finding.code for finding in findings}
        if status != "FAIL" or "same_page_anchor_missing" not in codes:
            raise AssertionError(render_text(status, manifest(root), findings))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default=ROOT.as_posix(), help="Repository root to audit.")
    parser.add_argument("--format", choices=("text", "json"), default="text")
    parser.add_argument("--no-render-check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()

    if args.self_test:
        self_test()
        print("[tds-surface] self-test PASS")
        return 0

    status, current_manifest, findings = audit(Path(args.target), run_render_check=not args.no_render_check)
    if args.format == "json":
        print(json.dumps({"status": status, "manifest": current_manifest, "findings": [finding.as_dict() for finding in findings]}, indent=2))
    else:
        print(render_text(status, current_manifest, findings))
    return 1 if status == "FAIL" else 0


if __name__ == "__main__":
    raise SystemExit(main())
